title: "Megalos World Wiki"
author: "Megalos Corp © 2021"
email: "Contact@megaloscorp.onmicrosoft.com"

theme: minima

header_pages:
  - informations.md
  - commandes.md
  - craft.md
  - distrib.md

  minima:
    social_links:
      youtube: Mégalos Team
      youtube_channel: UCgc0DywR9jbN1-oT5fc0LHw
      youtube_channel_name: Mégalos Team
